# This is a basic workflow to help you get started with Actions

name: React_Live

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # Runs a set of commands using the runners shell
      - name: npm install and npm run build
        run: |
          npm i
          npm run build
          
      - name: Delete Existing Files
        run : sudo sshpass -p ${{ secrets.SSH_PASS }} -v ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'cd /home/it_idol_dev/Projects/var/www/html && chmod -R 777 test-reactjs-cicd && rm -rf /home/it_idol_dev/Projects/var/www/html/test-reactjs-cicd'

      - name: Compress and Copy New Files to server
        run : |
              cp .htaccess build/
              cd build/
              sudo sshpass -p ${{ secrets.SSH_PASS }} scp -v -o StrictHostKeyChecking=no -r test-reactjs-cicd ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/it_idol_dev/Projects/var/www/html

      - name: Folder Permission
        run : sudo sshpass -p ${{ secrets.SSH_PASS }} -v ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'cd /home/it_idol_dev/Projects/var/www/html && chmod -R 777 test-reactjs-cicd'

      #- name: Uncompress new Files
      #  run : sudo sshpass -p ${{ secrets.SSH_PASS }} -v ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'cd /home/it_idol_dev/Projects/var/www/html && chmod -R 777 test-reactjs-cicd.tar.gz && tar -xzvf test-reactjs-cicd.tar.gz && chmod -R 777 test-reactjs-cicd && rm -rf test-reactjs-cicd.tar.gz'

      #- name: Add .htaccess file
      #  run : sudo sshpass -p ${{ secrets.SSH_PASS }} scp -v -o StrictHostKeyChecking=no -r .htaccess ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/it_idol_dev/Projects/var/www/html/test-reactjs-cicd/

      #- name: Add .htaccess file 
      #  run : sudo sshpass -p ${{ secrets.SSH_PASS }} scp -v -o StrictHostKeyChecking=no -r .htaccess ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/it_idol_dev/Projects/var/www/html/test-reactjs-cicd/